# Generated by Django 5.1.5 on 2025-01-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_convenio', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('horario_atendimento', models.CharField(max_length=13)),
                ('especialidade', models.CharField(max_length=75)),
                ('lotacao_atual', models.IntegerField()),
                ('tempo_medio_espera', models.DurationField()),
                ('convenio', models.ManyToManyField(to='map.convenio')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_atendimento', to='map.endereco')),
            ],
        ),
    ]
