# Generated by Django 5.1.5 on 2025-03-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_condicao_sintoma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triagem',
            old_name='gravidez',
            new_name='gravidade',
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_doenca', models.CharField(max_length=75)),
                ('gravidade_doenca', models.IntegerField()),
                ('sintomas_doenca', models.ManyToManyField(to='map.sintoma')),
            ],
        ),
    ]
