# Generated by Django 5.1.5 on 2025-03-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_rename_gravidez_triagem_gravidade_doenca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadeatendimento',
            name='tempo_medio_espera',
        ),
        migrations.AddField(
            model_name='sintoma',
            name='parte_corpo',
            field=models.CharField(default='Geral', max_length=45),
            preserve_default=False,
        ),
    ]
