# Generated by Django 5.1.5 on 2025-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_remove_unidadeatendimento_tempo_medio_espera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='gravidade',
            field=models.IntegerField(null=True),
        ),
    ]
