# Generated by Django 5.1.5 on 2025-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_triagem_gravidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='data_realizacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='horario_realizacao',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
