# Generated by Django 5.1.5 on 2025-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_triagem_data_realizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dt_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
