# Generated by Django 5.1.5 on 2025-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_usuario_dt_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=1234, max_length=40),
            preserve_default=False,
        ),
    ]
