# Generated by Django 5.1.5 on 2025-03-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
