# Generated by Django 5.1.5 on 2025-03-24 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_remove_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.convenio'),
        ),
    ]
