# Generated by Django 5.1.5 on 2025-03-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_remove_usuario_groups_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeatendimento',
            name='nivel_atendimento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
